networks:
  main:
    driver: bridge

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'db-user'
      POSTGRES_PASSWORD: 'db-password'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U db-user -d test']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - main
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
